### ISSUE TITLE
Plugin makes site extremely slow with >500 products

### ISSUE THREAD

**Issue by WiredWonder** [Go-Shippit/Woo-Commerce#1]
Hi guys (Matthew?),

I have a site with approx 2500 products.  When I enabled Shippit for WooCommerce, I found the site would slow to a crawl and run into out of memory errors (despite raising the per process limit to over 200MB).  This was most noticeable on an Add To Cart.  

Using WP Debug I found a huge query that was retrieving the product taxonomy data for every single product in the site in one query, taking >500ms and using >150MB.

The culprit seems to be something in /includes/class-shippit-settings-method.php which is retrieving each and every product.  If I comment out lines 195-201, or bypass the if statement on line 101, the query is not executed and memory usage returns to sane levels.  By my reading this code should only need to execute on the settings page so I have no idea why it's executing on an Add To Cart.

Interestingly a comment above line 101 this says the method is about to be deprecated so maybe you're already onto it.

Hopefully this issue log is monitored and you guys can address.  I am sure this will provide performance improvements even on smaller sites.

Cheers,
Jason

**Comment by matthew-muscat** [comment]
Hi Jason,

Thanks for the issue report

https://github.com/Go-Shippit/Woo-Commerce/blob/master/includes/class-shippit-settings-method.php#L122

Yes, this area of the configuration loads each product so that we can offer the ability to filter out certain products from being quoted by Shippit — unfortunately, this area appears to be loaded on each page load, rather than only when the settings area is rendered, which is certainly not ideal, and can cause performance issues for sites with larger catalogs.

We had planned to depreciate this functionality, but we're also weary of breaking changes that would affect existing merchants.

I'll liaise with the team here and see what can be done — ideally, we'll just remove this option — but if we still need to maintain backwards support an option available to use would include changing this from a populated select field, over to a field of comma separated product ids.

The underlying query causing the issues is located at https://github.com/Go-Shippit/Woo-Commerce/blob/master/includes/class-shippit-settings-method.php#L194 — which is querying all products to retrieve the select options.

**Comment by matthew-muscat** [comment]
Hi @galapogos01,

We've just pushed out a bugfix release that includes a workaround for the issue you are encountering, while still maintaining backwards support for existing merchants.

Simply set the constant `SHIPPIT_DISABLE_PRODUCT_FILTER` to your `wp-config.php` file and the plugin will avoid running this logic in v1.4.5

This fix was merged in on https://github.com/Go-Shippit/Woo-Commerce/commit/3a1c80c70e3749e4398e0a95156339ba849a03a0
